import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/ui/Header";
import { ThemeSeedProvider } from "@/components/providers/ThemeSeedProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className="antialiased min-h-screen bg-slate-50 text-slate-900"
      >
        <ThemeSeedProvider>
          <div className="min-h-screen flex flex-col">
            <Header />
            <main className="flex-1">
              <div className="max-w-4xl mx-auto px-4 py-6">
                {children}
              </div>
            </main>
            <footer className="border-t bg-white">
              <div className="max-w-4xl mx-auto px-4 py-3 text-xs text-slate-500">
                © {new Date().getFullYear()} one-minute-memo
              </div>
            </footer>
          </div>
        </ThemeSeedProvider>
      </body>
    </html>
  );
}
